### ISSUE TITLE
Masked array as index?

### ISSUE THREAD

**Issue by mdhaber** [mdhaber/marray#24]
I'm not certain how indexing with a masked array should work. IIUC, indexing with a NumPy masked array is identical to indexing with the masked array's data; the mask is simply ignored. But there are other conceivable behaviors, so it's worth some discussion. For now, there is no special handling - the behavior is defined by the most straightforward implementation of `__getitem__` and `__setitem__`.

**Comment by keewis** [comment]
I would actually forbid indexing with masked arrays for now until we have a use case for it. It is easy enough to explicitly extract the data, and it is always easier to add a new feature than removing one.

**Comment by mdhaber** [comment]
That sounds good.

**Comment by mdhaber** [comment]
@keewis (and @lucascolley, @seberg maybe, I'd appreciate your thoughts, too).

I had to re-open this due to gh-97; we're going to run into cases where a masked array is indexed by a masked array *with masked elements*. For instance, it is common to index like `x[x == 1]`, so if `x` has masked elements, the index has masked elements.

Here are the options that were obvious to me for defining `x[i]`:
1. Use the `i.data` as the index, ignoring `i.mask`, i.e. `x[i.data]`.
2. Treat masked elements as `False`, i.e. `x[i]` is `x[i.data & ~i.mask]`.
3. Use the `i.data` as the index, but consider `i.mask` in the mask of the output, i.e. `x]i]` is `asarray(x.data[i.data], mask=(x.mask | i.mask)[i.data])`.

There may be other properties that should hold, but these are the ones I've identified:
1. `x[i]` should not treat masked `True`s the same as unmasked `True`s.
2. `x[i].size + x[~i].size` should equal `x.size`.

(Of course , there is also Property 0, that when wherever `i.mask` is `True`, it should behave just like indexing with a regular array. So really we're just focusing on what happens when indices are masked.)

Because of Property 1, I'd think option 1 could be rejected outright. Of course, option 1 is what NumPy masked arrays do. 
```python3
import numpy as np
x_val = np.arange(8)
x_mask = [False, False, False, False, True, True, True, True]
i_val = [False, False, True, True, False, False, True, True]
i_mask = [False, True, False, True, False, True, False, True]
x = np.ma.masked_array(x_val, mask=x_mask)
i = np.ma.masked_array(i_val, mask=i_mask)
x[i]
# masked_array(data=[2, 3, --, --],
#              mask=[False, False,  True,  True],
#        fill_value=999999)
x[i.data]
# masked_array(data=[2, 3, --, --],
#              mask=[False, False,  True,  True],
#        fill_value=999999)
```

Requiring Property 2 would rule out Option 2.
```python3
from marray import numpy as mxp
x = mxp.asarray(x_val, mask=x_mask)
i = mxp.asarray(i_val, mask=i_mask)
x[i.data & ~i.mask]
# MArray(array([2, _]), array([False,  True]))
x[(~i).data & ~(~i).mask]
# MArray(array([0, _]), array([False,  True]))
```
The total number of elements left is four, but we started with eight.

Option 3 satisfies both properties, so I'm inclined to go that way.
```python3
mxp.asarray(x.data[i.data], mask=(x.mask | i.mask)[i.data])
# MArray(array([2, _, _, _]), array([False,  True,  True,  True]))
mxp.asarray(x.data[(~i).data], mask=(x.mask | (~i).mask)[(~i).data])
# MArray(array([0, _, _, _]), array([False,  True,  True,  True]))
```

Thoughts?

**Comment by seberg** [comment]
For boolean indexing, both the options you said seem OK on first sight:
* Consider `NA`/masked as "not True", or
* Raise an error because `NA` is neither true nor false.

I would check what dataframe libraries do, although pandas differing with `.iloc` (always raises) and direct indexing is a bit tricky.  (It also seems not unlikely that both options are in use in various libraries.)

It seems to me that `series[integer_index]` raises in pandas (my feeling was that propagating NA might be fine there, but maybe it leads to confusion somewhere?), while `series[bool_index]` consider `NA` as "not true".

One property that should hold for boolean indexing is: `x[boolean_indx].size == boolean_indx.sum()/boolean_indx.count_nonzero()`.  But, I suppose the `sum()` will returns the number of Trues, so it doesn't really matter for the choice.

**Comment by crusaderky** [comment]
Option 3 sounds the only sane one to me too.

**Comment by seberg** [comment]
I feel compelled to state more explicitly that option 3 seems very strange to me (for boolean indexing).  And if you like a formalized argument:
1. It must breaks `x[boolean_indx].size == boolean_indx.sum()` (because of 2.)
2. I find it scary that the result would *ever* depend on the actual value of a masked value.  First, are you sure you can properly propagate "good" values always?  (`numpy.ma` pretends a bit it can, but then often just propagates "fill values" and terribly so).
   Even if you can propagate them, in many use cases the user will never have had a valid underlying value for the masked value and might fill it with garbage (in some way or another).

If you want to ensure `x[i].size + x[~i].size`, that is fine!  But then to me the only sane option is to just raise an error.

Or am I misunderstanding option 3/missing that you always expect the masked value to have a reasonable meaning?  (Some masked array implementations don't even allow dragging around an actual value, although not sure that this is many.)

For integer indexing, my gut feeling would have been that option 3 is fine (it doesn't suffer from those two points above).  (Although, even there you don't want an index error depending on the value under the mask.  Also, I would want to ask a pandas/dataframe dev if there are good reasons why pandas seems to rejects it.)

**Comment by crusaderky** [comment]
> 1. It must breaks `x[boolean_indx].size == boolean_indx.sum()` (because of 2.)

I don't see a particularly big problem with that.
Before applying the mask, the number of "good" points in x was potentially already less than its size.

> I find it scary that the result would ever depend on the actual value of a masked value.

But it doesn't though? Filtering by a masked index gives you a masked output. You're just carrying the garbage points around.

> you always expect the masked value to have a reasonable meaning? 

I thought the meaning was "this point is junk, and any point that is produced as a function of it is also junk"?

**Comment by seberg** [comment]
> But it doesn't though? Filtering by a masked index gives you a masked output.

But that is the point, that this is clearly not true as spelled out above!  You are using `arr[index.data]` (and then masking).  So the a `arr[[masked(True)]] -> make_masked(arr[[True]]) -> make_masked([value]) -> [masked]`, while a `arr[[masked(False)]] -> arr[[False]] -> []`!

> I thought the meaning was "this point is junk, and any point that is produced as a function of it is also junk"?

Yes, but if the result (i.e. its size) changes based on that junk value, than it clearly can't be junk anymore?

**Comment by crusaderky** [comment]
I continue not to see the problem.
A masked array is an array that carries around junk points. To my understanding `[]` and `[masked]` are identical in terms of information: both contain zero good points. The only reason that you want one or the other is to satisfy numpy's geometry quirks (such as making masked updates `a[i] = b[i]` work) - this is because numpy can be seen as an indexed database, where the index is the n-dimensional coordinate of each point.

**Comment by seberg** [comment]
In general, I strongly disagree it doesn't matter.  Specifically in the context of boolean indexing I find it very odd, but it may be OK.

But if you do that, you are going full circle IMO:  If it doesn't matter whether masked values are included in the result or not, you should just treat them as `False` and _never_ include them, for everyones sanity.

If the `arr[mask].size` is random, then the `arr[mask].size + arr[~mask].size == arr.size` property, IMO, becomes pretty much meaningless anyway.
(Also, what if a masked array implementation doesn't have a value and uses kleene logic: `~NA == NA` in that case that identity is also broken anyway.)

**Comment by lucascolley** [comment]
> kleene logic

Haha, I'm getting to use the Philosophy half of my degree for once! Drawing from the lecture notes for one of my courses, we have (at least) a few options:

<img width="787" alt="Image" src="https://github.com/user-attachments/assets/7951b0ad-2bd0-4319-bf4a-7bc27fc7593a" />

Being true to 'Weak Kleene', I think we would want to produce a masked element wherever `i.mask`, regardless of `i.data`.

<img width="791" alt="Image" src="https://github.com/user-attachments/assets/6ac46cee-1a95-46fb-a8d6-1df66aa84446" />

In Kleene, we can think of it as performing computation for each possible value (`0` or `1`), outputting the unique result if there is one, else outputting `NA`.

Whenever `x[i.data]` and `x[(~i).data]` disagree, then *(this is always, right?)*, we would want the value to be masked. So again, we want to produce a masked element wherever `i.mask`, regardless of `i.data`.

<img width="717" alt="Image" src="https://github.com/user-attachments/assets/aa0ef792-99a2-4914-90ec-fe95fcbb1873" />

Here, we can treat masked values as always acting like either `1` or `0` (never both)—we just don't know which. But again, since we don't know whether the index is supposed to be truthy or falsy, I think we ought to output a masked value.

Finally, there is the Logic of Paradox by Priest (1979), where the third truth value indicates *both* true and false (i.e. paradoxical). We have the same truth tables as Kleene, but since the third truth value _is_ truthy, this gives justification to ignoring `i.mask` and just applying `i.data` (like NumPy). Yet _paradoxically_, it also gives justification for Sebastian's suggestion of treating masked values as false, and never including them.

---

All this is to say that we might be in Philosophical hot water by trying to treat a certain behaviour as "correct". Perhaps the least controversial would be to always produce a masked output wherever `i.mask`. I think this would also violate property 2, but maybe that isn't a bad thing?

**Comment by mdhaber** [comment]
> All this is to say that we might be in Philosophical hot water by trying to treat a certain behaviour as "correct

Just wanted to mention that I agree that *correctness* is not on the table. Masked arrays seem inconsistent to me in the difference between `sum([x, y])` and `x + y`. What's *useful* and easy to use is all I'm going for.

**Comment by crusaderky** [comment]
> ISTM that Option 2 would result in unmasked values of the empty array, whereas Option 3 would mask them. RIght? That is not to say that Option 3 does not have gotchas. But this is a data point.

Correct. With option 2, lazywhere would need to have an explicit marray-specific masking pass:
```python
out = xp.empty(cond.shape, dtype=dtype)
temp1 = xp.asarray(f(*(arr[cond] for arr in arrays)))
out[cond] = temp1
ncond = ~cond
temp2 = xp.asarray(f2(*(arr[ncond] for arr in arrays)))
out[ncond] = temp2

# marray-specific finalization
mask = functools.reduce(operator.or_, arr.mask, [arr.mask for arr in arrays])
out = xp.asarray(out, mask=mask)
```

> If the `arr[mask].size` is random

Not random in the slightest. In option 2 it is data-dependeent and mask-dependent; in option 3 it is data-dependent and mask-independent.

**Comment by lucascolley** [comment]
Assuming that we treat a masked `0` the same as a masked `1`, i.e. `NA`, `x[i]`:
<table>
<tr>
 <td>`x`
 <td>`i`
 <td> Result
<tr>
 <td> 0
 <td> 0
 <td> not included
<tr>
 <td> 1
 <td> 0
 <td> not included
<tr>
 <td> NA
 <td> 0
 <td> not included
<tr>
 <td> 0
 <td> 1
 <td> 0
<tr>
 <td> 1
 <td> 1
 <td> 1
<tr>
 <td> NA
 <td> 1
 <td> NA
<tr>
 <td> 0
 <td> NA
 <td> logic of paradox seems to justify either not including it, or including 0. The other logics seem to justify including NA.
<tr>
 <td> 1
 <td> NA
 <td> logic of paradox seems to justify either not including it, or including 1. The other logics seem to justify including NA.
<tr>
 <td> NA
 <td> NA
 <td> logic of paradox seems to justify either not including it, or including NA. The other logics seem to justify including NA.
</table>

Matt's option 2 seems to align with one of the options which fits with the logic of paradox interpretation. The other logics seem to align with an option 4, which is to always included a masked value.

---

IIUC, option 3 is suggesting that our assumption that a masked `0` is the same as a masked `1` is wrong—if we have a masked `0`, we ought not to include the corresponding value. Whereas, if we have a masked `1`, we ought to include a masked value. Is that right @mdhaber ?

**Comment by lucascolley** [comment]
To implement option 4, we would need to:

1. drop values where the index is an unmasked `0`
2. mask the output wherever the index is masked (or the data is masked)

So indeed, as you have written.

**Comment by lucascolley** [comment]
> I like from a theoretical perspective that masked True/False are treated the same way rather than (arbitrarily, since masked values are garbage) affecting the size attribute (even if the size attribute doesn't matter).

This seems pretty damning for Option 3, if we are treating 'masked values are garbage' as the most common use-case.

**Comment by mdhaber** [comment]
I'm not sure though. The point is that masked values should not affect the *numerical result* of numerical calculations.

**Comment by mdhaber** [comment]
> Ah, you want it to work without anything mask specific, OK I guess that would be neat, although I do wonder how far you will get in practice.

Not super far. Absolutely masks need to be considered explicitly sometimes. I just mean it would be nice to *reduce* gotchas where possible.

> I personally see raising an error as perfectly valid as well,

But that's what we're trying to avoid.
@crusaderky can you point to a branch where the sort of failures you've mentioned in gh-97 will occur? I think it would be helpful to have an example of a situation in which masked input to a stats function leads to these errors.

**Comment by seberg** [comment]
Well, `lazywhere` just can't work, I think, because assignment with NAs has to be "weird":
```
arr = [1, 2, 3]
res = arr[[True, NA, False]] = [10, 20]  # must be 2 values for option 4

res == [10, NA, 3]
```
I.e., surely assignment with NA can't cause filling in a non-NA value?  And retaining the old value seems also odd?

> But that's what we're trying to avoid.

That is fair, but I'll just say again that the only obvious choice there is option 2 (because that is common prior art in dataframes/SQL, etc., unless you have other prior art).
So if you can't confidently settle on option 2 but also don't have _very_ compelling arguments for 4 (for me that should include some prior art/use-case)...

... Then sticking with the error is just by far best option left.

**Comment by mdhaber** [comment]
@seberg Can you give code snippets of the prior art you're referring to like I have for `numpy.ma`?

**Comment by seberg** [comment]
I mean for example:
```
import pandas as pd
s = pd.Series([1, 2, NA, 1, 3], dtype="Int64")

s[s == 1]
```

**Comment by mdhaber** [comment]
```python3
import pandas as pd
x = pd.Series([False, False, False, True, True, True, pd.NA, pd.NA, pd.NA], dtype="Int64")
i = pd.Series([False, True, pd.NA, False, True, pd.NA, False, True, pd.NA], dtype="boolean")
print(x[i])
# 1       0
# 4       1
# 7    <NA>
# dtype: Int64
print(x[~i])
# 0       0
# 3       1
# 6    <NA>
# dtype: Int64
```

**Comment by keewis** [comment]
For integer indices I'd probably try to keep the property of `x[i].size == i.size`, and mask all values that were masked on the index, i.e. `x[i].mask == x.mask | i.mask`. Since this has not been discussed as much I guess that's pretty much agreed on, right?

For boolean arrays where the array size is data-dependent I'm less sure. If I'm reading the comparison with `pandas` from https://github.com/mdhaber/marray/issues/24#issuecomment-2741553165 correctly, it looks like they're treating `NA` like `False` (which I would have naively done as well). In other words, option 2: `x[i].size + x[~i].size + x[i.mask].size == x.size`.

**Comment by seberg** [comment]
> Yeah, NumPy ; ) That just shows that it's up for debate!

Well, for numpy masked arrays, it is very unclear whether there was any intention in it, or it isn't just inherited carelessly.
So yeah, I don't give that a lot of weight without knowing that there was intention or use there :).

**Comment by crusaderky** [comment]
I think that the `size` argument is moot.
In a perfect world, `size` would be `x.mask.sum()`, but can't because it would be very expensive on eager wrapped backends and outright impossible on lazy ones.
The array API states that `size` is the _"Number of elements in an array"_. It doesn't say that they need to be _good_ elements.

What _does_ matter is that `a[i | ~i]` must fully cover `a`, and it's perfectly reasonable to me that it does so by masking any element of `a` that is masked in `i`. In other words: a masked point should be interpreted as "the data at these coordinates is garbage"; not "there is no data at these coordinates". Everything that the garbage point touches (by means of a elementwise operation) is turned to garbage too. There is an explicit stipulation that _reductions_ skip garbage, which is notably the opposite stipulation as Array API treatment of NaN and the same as pandas default treatment for NaN. What I'm pushing here is that masks should behave the same as elementwise operations.

**Comment by lucascolley** [comment]
> it's perfectly reasonable to me that it does so by masking any element of a that is masked in i. In other words: a masked point should be interpreted as "the data at these coordinates is garbage"; not "there is no data at these coordinates". Everything that the garbage point touches (by means of a elementwise operation) is turned to garbage too.

Does that align with option 4?

**Comment by crusaderky** [comment]
Yes. I think that option 3 and 4 are equally valid, with option 3 being more performant as it takes the opportunity to get rid of garbage.

**Comment by lucascolley** [comment]
>  I think that option 3 and 4 are equally functionally valid

Are you comfortable with option 3 treating a masked `0` differently from a masked `1`?

**Comment by seberg** [comment]
> What I'm pushing here is that masks should behave the same as elementwise operations.

Right, this is a choice NaNs are usually a "poinsoness" value, while `NA` in dataframes is more the meaning of a "missing" (let's lean to ignoring it) value.

Both make sense (and even mixing in principle)!  From the missing values perspective, it turns out what you almost always want is to ignore NAs by default for all forms of *aggregations*, while for NaNs we (e.g. NumPy) poisons the aggregation.  (Actually, IEEE has an `fsum` that ignores NaNs and no `sum`, although I guess that may be because `sum` is trivial.)

In most cases we use boolean indexing as a preparation for an aggregation (i.e. `arr[mask].sum()`) and for that all choices here are actually equivalent anyway.
But, overall I do see boolean indexing more as an aggregation (e.g. it operates on many elements, not on a clear fixed number).  But I would agree that boolean indexing doesn't matches neither "aggregation" or "elementwise operation".

**Comment by lucascolley** [comment]
>>But again, since we don't know whether the index is supposed to be truthy or falsy, I think we ought to output a masked value.
>
> This makes sense to me for integer indexing. But for boolean indexing it isn't quite so simple, since the possible results are [value] and [] and not value1 and value2. But yeah, always including is maybe an option.

Right, the problem is that we are looking for a superposition of included and not included, which is not practical at all. The question I have is whether including a masked value or not including any value is a more true/useful representation of that. I think that including the value based on `i.data` seems to be disrespecting the fact that the data is masked.

If we wanted to be conservative, I suppose including a masked value is less "destructive"? We'd probably have to see real use-cases though.

**Comment by crusaderky** [comment]
> > I think that option 3 and 4 are equally functionally valid
> 
> Are you comfortable with option 3 treating a masked `0` differently from a masked `1` (in the index)?

Yes, I am comfortable with throwing out garbage when it is safe to do so, instead of carrying it around and continuing to ignore it.
Again, the two approaches are functionally equivalent, with the former being more performant.

> > What does matter is that a[i | ~i] must fully cover a
> 
> Isn't that asking for the impossible? `i | ~i` effectively _never_ covers `NA` elements in `i` as you would mask the result anyway.

`NA` elements in `i` cover the matching elements in `a` by setting them to `NA`.

> Unless you argue that the user may work with `arr.data` directly (uncovering it on the result)? 

I am not. masked points are garbage and any direct operation on them must be for performance reasons only, treating the output as garbage.

> But even if you want that, we just lose where the `NA` came from (`a` or `i`), so I think the user should instead uncover `a` or `i` before.

I don't care where the `NA` came from, for the same reason that a reduction or an elementwise operation of an array of NaNs will result in NaN without caring where it came from.

> The only argument here I see is that having an `NA` in the result warns you about NA in the index, however, your option 3 doesn't even do that reliably.

The argument for having an `NA` in the result is to make `a[i | ~i]` fully cover `a`, by virtue of either value or mask.

> `a[mask] = a[mask]` should likely keep `a` unchanged

I disagree. An `NA` point of the mask informs that the point is garbage.

> If we wanted to be conservative, I suppose including a masked value is less "destructive"? We'd probably have to see real use-cases though.

A real use-case is `_lazywhere`: https://github.com/mdhaber/marray/issues/24#issuecomment-2741374338

**Comment by seberg** [comment]
> A real use-case is _lazywhere

Did we even define what that `where` should do `NA` values in the condition!?  With your preference I suppose you have something like:
```
idx = [True, -True-, False, -False-]  # -True- being masked
arr[idx] = 1  # sets elements 1 and 2
# NOTE: relies ~idx not skipping masked elements!  (e.g. NumPy doesn't generally guarantee such behavior in masked arrays!)
assert ~idx == [False, -False-, True, -True-]
arr[~idx] = 2  # sets elements 3, 4
```

But that also means that:
```
arr[[True, -True-]] = 3
```
sets everything to 3!  I can see setting `arr[1]` to `NA` there or maybe keeping it unchanged, but changing it seems a hard sell to me.

Now `where` is tricky, since you could also define the correct result as `NA`/neither when the condition is `NA` (pandas actually treats NA as falsy in its `where`, not sure that is a good choice, but if that was the choice I don't think anything option can work).

If you choose that NA condition should give an NA result *both* option 2 and option 4 give the correct thing, I think.  For option 2 that assumes that `empty` returns an all masked array.  For option 4 it assumes that NA leads to an NA in the result.

Now to option 4 and why I say assignments may be tricky:
```
arr == [1, 2]

assert arr[[True, --]] == [1, --]

arr[[True, --]] = arr[[True, --]]

assert arr == [1, --]  # changed arr with what looks like a no-op!
```
doesn't round-trip.  Which maybe you can ignore, but I think that needs saying.

**Comment by mdhaber** [comment]
> But that also means that:

@seberg it appears you're using an array of size 2 to index an array of size 4?

Also, are `-True-`, `NA`, and `--` all equivalent in that post, meaning masked element?

> Now to option 4 and why I say assignments may be tricky... Which maybe you can ignore, but I think that needs saying.

That is worth saying, but like @crusaderky, I'm not sure it's problematic. In the implementation of `_lazywhere` above, it is actually a feature: a masked index means that something corresponding with that index is masked. Boolean masks are elementwise, so it makes some sense for the mask in that element to propagate.

If `x` is an array of shape `(1,)`:
- `x[True] = 1` sets the element to 1
- `x[False] = 1` leaves it alone
- `x[mxp.asarray([False], mask=[True]) = 1` and  `x[mxp.asarray([True], mask=[True]) = 1` mask the element.

Agreed that from previous experience I would expect `x[i] = x[i]` to be a no-op, but I think I can accept that this is not the case with masked arrays, and it would be something to point out in a tutorial. 

This does bring up that `x[i] = x[i]` needs to be a no-op for integer indices, though, since the value of a masked integer index must be meaningless. More specifically, `x[i]=` cannot modify elements where `i` is masked. Yes, that would be a difference between integer and Boolean indexing.

**Comment by seberg** [comment]
> @seberg it appears you're using an array of size 2 to index an array of size 4?

That was supposed to be just a new example, and two entries are enough.

Right, I used `NA` sometimes then switched to `--` and forgot to change it everywhere.  `-True-` *is* important, because for those example the value under the mask matters!

> but I think I can accept that this is not the case with masked arrays, and it would be something to point out in a tutorial.

Yes, that is probably fair (I haven't thought it through if I think this is a problem).  I am pointing it out, because I think it would be wrong to just miss this in the whole discussion.

The fact is that for option 2 it does remain a no-op, which probably is a point in favor of it (if maybe a small one).

**Comment by crusaderky** [comment]
> But that also means that:
> 
> ```
> arr[[True, -True-]] = 3
> ```
> 
> sets everything to 3! 

No, it doesn't. `arr[[True, -True-]] = 3` sets `arr` to `[3, NA]`.
Just like `arr[[True, -False-]] = 3` does.
 The value of `arr.data[1]` after either operation is inconsequential, beause `arr.mask[1]` is True.

**Comment by seberg** [comment]
Fair, that was a mind-slip there, because it is what NumPy's `ma` currently does, and somehow I thought that would match up (but you _could_ update the mask fully an assignments)!
I still suspect there may be surprises here, around things like, but it doesn't really matter:
```
arr[[True, -True-]] = [1, 2]  # does this work or not if option 3 is what you do?
```

But can't we just agree that Option 3 accepts that the result length is *undefined* (i.e. the "garbage" matters for the result length)?
And because of that strangeness, that option 4 is clearly preferable? [^mask-optimization]

With that we can go back and say that there are really three options:
* Option 2: Consider NAs as Falsy (as pandas, etc.)
* Option 4: Propagate NAs as NA values (both in assignment and indexing).  Not sure if anyone quite does this.
* Option 0: Keep things an error because we can't decide

compare in practice?

I still have some doubts about options 4 and assignment/round-tripping and also about whether it isn't just the less convenient thing, but that isn't like my serious dislike for option 3 ;).


[^mask-optimization]: And this matters, if a little, because `~i` shouldn't promise that the garbage is inverted, so it might be that both `i` and `~i` contain no or all NAs anyway.  This is not a problem for this implementation, but it can be a problem for an optimized/specialized masked array implementation (that doesn't want to operate or represent all masked values).

**Comment by mdhaber** [comment]
> Just like `arr[[True, -False-]] = 3` does.

Assuming Option 4 for `_setittem_`, right @crusaderky?

**Comment by mdhaber** [comment]
@crusaderky can you confirm that "Just like `arr[[True, -False-]] = 3` does." is true for Option 4 but not Option 3? Would this also move you toward 4 instead of 3?

**Comment by crusaderky** [comment]
Does the below implement correctly the two options?
(code omits the use case of idx not being an Array for the sake of brevity).

### Option 3
```python
def __getitem__(self, idx: Array) -> Array:
    data = self.data[idx.data]
    mask = (self.mask | idx.mask)[idx.data]
    return xp.asarray(data=data, mask=mask)

def __setitem__(self, idx: Array, value: Array | complex):
    if isinstance(value, int | float | complex):
        self.data[idx.data] = value
    else:
        self.data[idx.data] = value.data
        self.mask[idx.data] |= value.mask
    self.mask |= idx.mask
```

### Option 4
```python
def __getitem__(self, idx: Array) -> Array:
    i = idx.data & ~idx.mask
    return xp.asarray(data=self.data[i], mask=self.mask[i])

def __setitem__(self, idx: Array, value: Array | complex):
    i = idx.data & ~idx.mask
    if isinstance(value, int | float | complex):
        self.data[i] = value
    else:
        self.data[i] = value.data[~value.mask]
    # Needed to give `a[idx] = b; a[~idx] = c` full coverage
    self.mask |= idx.mask
```

It's worth noting that in option 4, in `__setitem__` `idx.mask` and `value.mask` must be aligned, whereas option 3 has no such problem. This _should_ not be a major concern in most cases.

Both option allow for `a[idx] = b[idx]` to work and both give full coverage to
```python
a = xp.empty(idx.shape)
a[idx] = b
a[~idx] = c
```
which are the two things I care about. So as stated before, **I'm happy to move on with either one**.


> [@crusaderky](https://github.com/crusaderky) can you confirm that "Just like `arr[[True, -False-]] = 3` does." is true for Option 4 but not Option 3? Would this also move you toward 4 instead of 3?

It is true both in option 3 and option 4, because they both have the line `self.mask |= idx.mask` in `__setitem__`.

**Comment by mdhaber** [comment]
No, I don't think that is the [Option 4](https://github.com/mdhaber/marray/issues/24#issuecomment-2741442316) we were discussing. That looks like Option 2, at least for `get_item`.

And the `self.mask |= idx.mask` is not really implied by the behavior of `__getitem__`. Fine to tack it on, but that's why I didn't think Option 3 would behave like that.

**Comment by crusaderky** [comment]
> No, I don't think that is the [Option 4](https://github.com/mdhaber/marray/issues/24#issuecomment-2741442316) we were discussing. That looks like Option 2, at least for `get_item`.

Could you post the full pseudocode for option 4, for my understanding?

The post you linked
```python
mxp.asarray(x.data[i.data | i.mask], mask=(x.mask | i.mask)[i.data | i.mask])
```
contains a logical error (i.data=True means "take", i.mask=True means "don't take"); it should be
```python
mxp.asarray(x.data[i.data & ~i.mask], mask=(x.mask | i.mask)[i.data & ~i.mask])
```
which is logically identical to what I wrote
```python
    i = idx.data & ~idx.mask
    return xp.asarray(data=self.data[i], mask=self.mask[i])
```
in my version, I don't bother doing the OR operation to the mask because I'm guaranteed that whatever is False in `idx.mask` is going to be removed by the indexing operation immediately afterwards.

**Comment by mdhaber** [comment]
I understood what you wrote, yup. 

Please take a second look at what I wrote. If there is a mistake, I still don't see it, and Lucas confirmed that is what he was describing. 

- Option 2 takes only the elements from `x` that correspond with unmasked Trues in `i`. (Your "corrected" version of my code.)
- Option 3 takes the elements from from `x` that correspond with Trues (masked or not) in `i`, masking the elements corresponding with masked indices.
- Option 4 takes the elements from from `x` that correspond with Trues *and all masked elements* in `i`, masking the elements corresponding with masked indices.

**Comment by crusaderky** [comment]
Thank you for the clarification. 
Is the below correct?

### Option 4
```python
def __getitem__(self, idx: Array) -> Array:
    i = idx.data | idx.mask
    return xp.asarray(data=self.data[i], mask=(self.mask | idx.mask)[i])

def __setitem__(self, idx: Array, value: Array | complex) -> None:
    if isinstance(value, int | float | complex):
        self.data[idx.data] = value
    else:
        i = idx.data | idx.mask
        self.data[i] = value.data
        self.mask[i] |= value.mask
    self.mask |= idx.mask
```
If yes, I'm happy with it.

**Comment by mdhaber** [comment]
For masked arrays, `_getitem_` is correct. 

(For clarity, let's ignore the `isinstance` check and such because `__getitem__` would still need one, and neither of these would work as written with regular, non-masked arrays.)

This part: `self.mask[i] |= value.mask` doesn't look right.  As written, masked elements are "infected" with the mask and even assignment can't cure it. I think there should only be assignment; `self`s mask need not be remembered where it's being assigned. And the assignment can be to whatever `__getitem__` would extract.

**Comment by lucascolley** [comment]
> `self`s mask need not be remembered where it's being assigned

right, conceptually I don't see anything wrong with (deliberately) overriding an invalid section of data with some new (valid) data

**Comment by mdhaber** [comment]
@lucascolley would you be willing to take another shot at this? I was thinking of working on CuPy testing this weekend. Would be great to get those things out of the way.

**Comment by lucascolley** [comment]
> would you be willing to take another shot at this?

what would that entail?
