### ISSUE TITLE
easier way to create arrays

### ISSUE THREAD

**Issue by keewis** [mdhaber/marray#6]
While the idea of using a function to create a nested namespace is neat, it makes creating arrays harder:
```python
import marray
import numpy as np

xp = marray.masked_array(np)

a = xp.asarray(np.arange(10))
a.mask[...] = np.arange(10) % 2 == 0
```
What I'd like to have (but don't quite know how easy it is to support, nor if it actually is a good idea) is something like this:
```python
import marray
import numpy as np

a = marray.MaskedArray(data=np.arange(10), mask=np.arange(10) % 2 == 0)
xp = a.__array_namespace__()  # nested namespace
```

Alternatively, this could also work (since the Array API doesn't forbid adding non-standard things to the namespace):
```python
xp = marray.masked_array(np)
a = xp.MaskedArray(data=np.arange(10), mask=np.arange(10) % 2 == 0)
```
However, I would imagine that this makes creating / composing arrays a bit harder. And since we don't subclass arrays classes anymore, maybe we don't even need the dynamic namespace (and thus the meta-programming)?

**Comment by mdhaber** [comment]
Your second example should work. And `asarray` also accepts the mask. Have you tried 

```python3
import marray
import numpy as np

xp = marray.masked_array(np)
a = xp.asarray(np.arange(10), mask=(np.arange(10) % 2 == 0))
```
?

Currently `mask` doesn't appear in the documentation, because it's just copied from NumPy, but that can come later.

**Comment by keewis** [comment]
That's interesting, I totally missed that. I was under the (quite possibly mistaken?) assumption that the Array API didn't allow adding additional arguments, so I didn't even bother to check.

**Comment by mdhaber** [comment]
I'm not certain, but NumPy 2.1 `asarray` has an `order` argument that is not in the standard.

**Comment by mdhaber** [comment]
@keewis this is now:

```python3
import marray
import numpy as np
mxp = marray.get_namespace(np)
a = mxp.asarray(np.arange(10), mask=(np.arange(10) % 2 == 0))
# MArray(
#     array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
#     array([ True, False,  True, False,  True, False,  True, False,  True,
#        False])
# )
```

which is no longer than the suggestions in https://github.com/mdhaber/marray/issues/6#issue-2677340080.

`marray` does not currently expose anything other than `get_namespace`. It is *possible* to expose a class `MArray` that infers the namespace from the arguments:

```python3
# draft just to illustrate
# subclasses might not work correctly as-written
class MArray:
    def __new__(self, data, mask=None):
        xp = data.__array_namespace__()
        mxp = get_namespace(xp)
        return mxp.MArray(data=data, mask=mask)
```

But my impression from your second suggestion is that four lines is short enough. Is this issue resolved?

**Comment by mdhaber** [comment]
> to make it clear, the requirement to create the namespace first feels inconvenient

It is possible to get around this for any function that accepts an array as input, but it is not without downsides.

- The documentation would be independent of the underlying array's documentation. 
- Array creation functions will not return arrays of the desired type unless we add an argument.
- You have to think a bit more about what to do when the user passes arrays of multiple types.
- Moreover, it requires a fair amount of internal restructuring. 

This is all quite a price to pay for users adding a single line in addition to the import. Maybe a MArray 2.0 thing, since almost nothing would change about user code? I'd rather get something working within the existing structure for now.

**Comment by mdhaber** [comment]
> other than feeling somewhat uneasy about modifying the signature of asarray, which I had believed should not be modified

We do not currently follow the positional-only, keyword-only conventions perfectly, so I think there are bigger fish to fry w.r.t. to the functions accepting more arguments than they should.

So that aside, with `mask` unspecified, we are (I think) exactly as array API compatible as the underlying library. With some elements masked, the behavior doesn't follow the array API; it is adapted for the presence of the mask. Why in that case does accepting a `mask` stand out as a problem?

**Comment by lucascolley** [comment]
closing now that we can use `asarray`, right?

**Comment by mdhaber** [comment]
I think so. I think the only possible alternative was that we *could* expose `MArray` as a class, and then it could be:
```python3
import numpy as np
import marray
x = marray.MArray([1, 2, 3])
```
So in theory you could instantiate an `MArray` and use its methods in three lines instead of four. But as soon as you need to get functions from the associated namespace, you'd need:
```
mxp = x.__array_namespace__()
```
adding an ugly fourth line. I don't think this is worth it, considering the alternative is also four line long, looks cleaner, and avoids having to make the `MArray` class public.

**Comment by keewis** [comment]
I was thinking that this pattern:
```python
import marray

x = marray.MArray(np.array([1, 2, 3]))
xp = x.__array_namespace__()
xp.exp(x)
```
was what you'd always get with the array API, unless you use the namespace directly (or at least, that was my impression when working on `xarray`).

Under that assumption the closest to ideal would be this:
```python
import marray as ma

x = ma.MArray(np.array([1, 2, 3]))
ma.exp(x)

# equivalent to
xp = x.__array_namespace__()
xp.exp(x)
```
but I guess since adding additional args / kwargs is explicitly allowed, the current state is fine.

I guess now the only issues I have is the registering of `mxp` in `sys.modules` (since calling `get_namespace` multiple times would overwrite the previously registered module), and that we don't have a way of doing `isinstance` checks for `MArray` if the class is not public. The latter can easily be resolved by a class that implements `__instancecheck__`, so nothing major (if you prefer I can open new issues for those, though)

**Comment by mdhaber** [comment]
> if you prefer I can open new issues for those, though

Pull requests would be even better! 

`strict` doesn't expose `Array`, right?

**Comment by lucascolley** [comment]
> Under that assumption the closest to ideal would be this:
> 
> ```python
> import marray as ma
> 
> x = ma.MArray(np.array([1, 2, 3]))
> ma.exp(x)
> ```

I think I disagree - this goes back to our discussion at https://github.com/data-apis/array-api/discussions/843#discussioncomment-10714668. Here's my reasoning:

`marray` in itself cannot be a standard-compatible namespace. While it is clear what `ma.exp(x)` should do, since `x` has an underlying array namespace, it is not clear what `ma.asarray([1])` should do, unless we introduce the concept of a default array backend. And like xarray (https://github.com/data-apis/array-api/issues/698#issuecomment-1800078933), I think it would be confusing to provide a namespace which has lots of functions which are in the standard, but misses some like `asarray`.

For xarray, a dispatching module like [`xarray.ufuncs`](https://docs.xarray.dev/en/stable/api.html#universal-functions) is needed, since `NamedArray`s are not compatible with the standard. But for libraries like marray which are compatible with the standard, and hence can provide `__array_namespace__`, I think using `xp = __array_namespace__` is the idiomatic way to interface.

---

Something that arises from this: in https://github.com/data-apis/array-api/discussions/843#discussioncomment-10714668 I discuss the idea of a `pint(dask(marray(sparse)))` array. I think `__array_namespace__().__name__` should be based on the name of the namespace of the array backend. So something like `marray(numpy)` rather than just `mxp`. Perhaps there should be some further discussion of this on the standard-side though - I'm not sure how this should interplay with things like `is_numpy_namespace` from array-api-compat.

**Comment by lucascolley** [comment]
To be clear about the problem I see with the current `__array_namespace__().__name__`:

```python
In [1]: import numpy as np

In [2]: import array_api_strict as xp

In [3]: import marray

In [4]: mnp = marray.get_namespace(np)

In [5]: mxp = marray.get_namespace(xp)

In [6]: xp1 = mnp.arange(2).__array_namespace__()

In [7]: xp1.__name__
Out[7]: 'mxp'

In [8]: xp1.arange(2).data.__array_namespace__().__name__
Out[8]: 'numpy'

In [9]: xp2 = mxp.arange(3).__array_namespace__()

In [10]: xp2.__name__
Out[10]: 'mxp'

In [11]: xp2.arange(3).data.__array_namespace__().__name__
Out[11]: 'array_api_strict'
```

The modules behave differently since they have different array backends, but have the same name.
